# https://book.getfoundry.sh/reference/config/overview

# presence of this file signals the base Foundry directory
[profile.default]

src = "contracts"

# remappings = [
# 	'@forge/=lib/forge-std/src/'
# ]
